# coding: utf-8

"""
    AI public API

    This API exposes AI metric & event information and associated metadata  # noqa: E501

    OpenAPI spec version: v1
    Contact: aiapi@microsoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.events_select import EventsSelect  # noqa: E501
from swagger_client.rest import ApiException


class TestEventsSelect(unittest.TestCase):
    """EventsSelect unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEventsSelect(self):
        """Test EventsSelect"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.events_select.EventsSelect()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
