# coding: utf-8

"""
    AI public API

    This API exposes AI metric & event information and associated metadata  # noqa: E501

    OpenAPI spec version: v1
    Contact: aiapi@microsoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_event(self):
        """Test case for get_event

        Get an event  # noqa: E501
        """
        pass

    def test_get_events(self):
        """Test case for get_events

        Execute OData query  # noqa: E501
        """
        pass

    def test_get_events_metadata_o_data(self):
        """Test case for get_events_metadata_o_data

        Get OData metadata  # noqa: E501
        """
        pass

    def test_get_metric(self):
        """Test case for get_metric

        Retrieve metric data  # noqa: E501
        """
        pass

    def test_get_metrics(self):
        """Test case for get_metrics

        Retrieve metric data  # noqa: E501
        """
        pass

    def test_get_metrics_metadata(self):
        """Test case for get_metrics_metadata

        Retrieve metric metatadata  # noqa: E501
        """
        pass

    def test_get_query(self):
        """Test case for get_query

        Execute an Analytics query  # noqa: E501
        """
        pass

    def test_get_query_schema(self):
        """Test case for get_query_schema

        Get Analytics query metadata  # noqa: E501
        """
        pass

    def test_query(self):
        """Test case for query

        Execute an Analytics query  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
