# coding: utf-8

"""
    AI public API

    This API exposes AI metric & event information and associated metadata  # noqa: E501

    OpenAPI spec version: v1
    Contact: aiapi@microsoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.error_response import ErrorResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestErrorResponse(unittest.TestCase):
    """ErrorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorResponse(self):
        """Test ErrorResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.error_response.ErrorResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
