# coding: utf-8

"""
    AI public API

    This API exposes AI metric & event information and associated metadata  # noqa: E501

    OpenAPI spec version: v1
    Contact: aiapi@microsoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.error_detail import ErrorDetail  # noqa: F401,E501
from swagger_client.models.error_info import ErrorInfo  # noqa: F401,E501


class ErrorInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code': 'str',
        'message': 'str',
        'details': 'list[ErrorDetail]',
        'innererror': 'ErrorInfo',
        'additional_properties': 'object'
    }

    attribute_map = {
        'code': 'code',
        'message': 'message',
        'details': 'details',
        'innererror': 'innererror',
        'additional_properties': 'additionalProperties'
    }

    def __init__(self, code=None, message=None, details=None, innererror=None, additional_properties=None):  # noqa: E501
        """ErrorInfo - a model defined in Swagger"""  # noqa: E501

        self._code = None
        self._message = None
        self._details = None
        self._innererror = None
        self._additional_properties = None
        self.discriminator = None

        self.code = code
        self.message = message
        if details is not None:
            self.details = details
        if innererror is not None:
            self.innererror = innererror
        if additional_properties is not None:
            self.additional_properties = additional_properties

    @property
    def code(self):
        """Gets the code of this ErrorInfo.  # noqa: E501

        A machine readable error code.  # noqa: E501

        :return: The code of this ErrorInfo.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this ErrorInfo.

        A machine readable error code.  # noqa: E501

        :param code: The code of this ErrorInfo.  # noqa: E501
        :type: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def message(self):
        """Gets the message of this ErrorInfo.  # noqa: E501

        A human readable error message.  # noqa: E501

        :return: The message of this ErrorInfo.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this ErrorInfo.

        A human readable error message.  # noqa: E501

        :param message: The message of this ErrorInfo.  # noqa: E501
        :type: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def details(self):
        """Gets the details of this ErrorInfo.  # noqa: E501

        error details.  # noqa: E501

        :return: The details of this ErrorInfo.  # noqa: E501
        :rtype: list[ErrorDetail]
        """
        return self._details

    @details.setter
    def details(self, details):
        """Sets the details of this ErrorInfo.

        error details.  # noqa: E501

        :param details: The details of this ErrorInfo.  # noqa: E501
        :type: list[ErrorDetail]
        """

        self._details = details

    @property
    def innererror(self):
        """Gets the innererror of this ErrorInfo.  # noqa: E501

        Inner error details if they exist.  # noqa: E501

        :return: The innererror of this ErrorInfo.  # noqa: E501
        :rtype: ErrorInfo
        """
        return self._innererror

    @innererror.setter
    def innererror(self, innererror):
        """Sets the innererror of this ErrorInfo.

        Inner error details if they exist.  # noqa: E501

        :param innererror: The innererror of this ErrorInfo.  # noqa: E501
        :type: ErrorInfo
        """

        self._innererror = innererror

    @property
    def additional_properties(self):
        """Gets the additional_properties of this ErrorInfo.  # noqa: E501


        :return: The additional_properties of this ErrorInfo.  # noqa: E501
        :rtype: object
        """
        return self._additional_properties

    @additional_properties.setter
    def additional_properties(self, additional_properties):
        """Sets the additional_properties of this ErrorInfo.


        :param additional_properties: The additional_properties of this ErrorInfo.  # noqa: E501
        :type: object
        """

        self._additional_properties = additional_properties

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ErrorInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
