# coding: utf-8

"""
    AI public API

    This API exposes AI metric & event information and associated metadata  # noqa: E501

    OpenAPI spec version: v1
    Contact: aiapi@microsoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ErrorDetail(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code': 'str',
        'message': 'str',
        'target': 'str',
        'value': 'str',
        'resources': 'list[str]',
        'additional_properties': 'object'
    }

    attribute_map = {
        'code': 'code',
        'message': 'message',
        'target': 'target',
        'value': 'value',
        'resources': 'resources',
        'additional_properties': 'additionalProperties'
    }

    def __init__(self, code=None, message=None, target=None, value=None, resources=None, additional_properties=None):  # noqa: E501
        """ErrorDetail - a model defined in Swagger"""  # noqa: E501

        self._code = None
        self._message = None
        self._target = None
        self._value = None
        self._resources = None
        self._additional_properties = None
        self.discriminator = None

        self.code = code
        self.message = message
        if target is not None:
            self.target = target
        if value is not None:
            self.value = value
        if resources is not None:
            self.resources = resources
        if additional_properties is not None:
            self.additional_properties = additional_properties

    @property
    def code(self):
        """Gets the code of this ErrorDetail.  # noqa: E501

        The error's code.  # noqa: E501

        :return: The code of this ErrorDetail.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this ErrorDetail.

        The error's code.  # noqa: E501

        :param code: The code of this ErrorDetail.  # noqa: E501
        :type: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def message(self):
        """Gets the message of this ErrorDetail.  # noqa: E501

        A human readable error message.  # noqa: E501

        :return: The message of this ErrorDetail.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this ErrorDetail.

        A human readable error message.  # noqa: E501

        :param message: The message of this ErrorDetail.  # noqa: E501
        :type: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def target(self):
        """Gets the target of this ErrorDetail.  # noqa: E501

        Indicates which property in the request is responsible for the error.  # noqa: E501

        :return: The target of this ErrorDetail.  # noqa: E501
        :rtype: str
        """
        return self._target

    @target.setter
    def target(self, target):
        """Sets the target of this ErrorDetail.

        Indicates which property in the request is responsible for the error.  # noqa: E501

        :param target: The target of this ErrorDetail.  # noqa: E501
        :type: str
        """

        self._target = target

    @property
    def value(self):
        """Gets the value of this ErrorDetail.  # noqa: E501

        Indicates which value in 'target' is responsible for the error.  # noqa: E501

        :return: The value of this ErrorDetail.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this ErrorDetail.

        Indicates which value in 'target' is responsible for the error.  # noqa: E501

        :param value: The value of this ErrorDetail.  # noqa: E501
        :type: str
        """

        self._value = value

    @property
    def resources(self):
        """Gets the resources of this ErrorDetail.  # noqa: E501

        Indicates resources which were responsible for the error.  # noqa: E501

        :return: The resources of this ErrorDetail.  # noqa: E501
        :rtype: list[str]
        """
        return self._resources

    @resources.setter
    def resources(self, resources):
        """Sets the resources of this ErrorDetail.

        Indicates resources which were responsible for the error.  # noqa: E501

        :param resources: The resources of this ErrorDetail.  # noqa: E501
        :type: list[str]
        """

        self._resources = resources

    @property
    def additional_properties(self):
        """Gets the additional_properties of this ErrorDetail.  # noqa: E501


        :return: The additional_properties of this ErrorDetail.  # noqa: E501
        :rtype: object
        """
        return self._additional_properties

    @additional_properties.setter
    def additional_properties(self, additional_properties):
        """Sets the additional_properties of this ErrorDetail.


        :param additional_properties: The additional_properties of this ErrorDetail.  # noqa: E501
        :type: object
        """

        self._additional_properties = additional_properties

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ErrorDetail):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
