# coding: utf-8

"""
    AI public API

    This API exposes AI metric & event information and associated metadata  # noqa: E501

    OpenAPI spec version: v1
    Contact: aiapi@microsoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class EventsPageViewInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'url': 'str',
        'duration': 'str',
        'performance_bucket': 'str'
    }

    attribute_map = {
        'name': 'name',
        'url': 'url',
        'duration': 'duration',
        'performance_bucket': 'performanceBucket'
    }

    def __init__(self, name=None, url=None, duration=None, performance_bucket=None):  # noqa: E501
        """EventsPageViewInfo - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._url = None
        self._duration = None
        self._performance_bucket = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if url is not None:
            self.url = url
        if duration is not None:
            self.duration = duration
        if performance_bucket is not None:
            self.performance_bucket = performance_bucket

    @property
    def name(self):
        """Gets the name of this EventsPageViewInfo.  # noqa: E501

        The name of the page  # noqa: E501

        :return: The name of this EventsPageViewInfo.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this EventsPageViewInfo.

        The name of the page  # noqa: E501

        :param name: The name of this EventsPageViewInfo.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def url(self):
        """Gets the url of this EventsPageViewInfo.  # noqa: E501

        The URL of the page  # noqa: E501

        :return: The url of this EventsPageViewInfo.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this EventsPageViewInfo.

        The URL of the page  # noqa: E501

        :param url: The url of this EventsPageViewInfo.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def duration(self):
        """Gets the duration of this EventsPageViewInfo.  # noqa: E501

        The duration of the page view  # noqa: E501

        :return: The duration of this EventsPageViewInfo.  # noqa: E501
        :rtype: str
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this EventsPageViewInfo.

        The duration of the page view  # noqa: E501

        :param duration: The duration of this EventsPageViewInfo.  # noqa: E501
        :type: str
        """

        self._duration = duration

    @property
    def performance_bucket(self):
        """Gets the performance_bucket of this EventsPageViewInfo.  # noqa: E501

        The performance bucket of the page view  # noqa: E501

        :return: The performance_bucket of this EventsPageViewInfo.  # noqa: E501
        :rtype: str
        """
        return self._performance_bucket

    @performance_bucket.setter
    def performance_bucket(self, performance_bucket):
        """Sets the performance_bucket of this EventsPageViewInfo.

        The performance bucket of the page view  # noqa: E501

        :param performance_bucket: The performance_bucket of this EventsPageViewInfo.  # noqa: E501
        :type: str
        """

        self._performance_bucket = performance_bucket

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EventsPageViewInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
