# coding: utf-8

"""
    AI public API

    This API exposes AI metric & event information and associated metadata  # noqa: E501

    OpenAPI spec version: v1
    Contact: aiapi@microsoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class EventsTraceInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'message': 'str',
        'severity_level': 'int'
    }

    attribute_map = {
        'message': 'message',
        'severity_level': 'severityLevel'
    }

    def __init__(self, message=None, severity_level=None):  # noqa: E501
        """EventsTraceInfo - a model defined in Swagger"""  # noqa: E501

        self._message = None
        self._severity_level = None
        self.discriminator = None

        if message is not None:
            self.message = message
        if severity_level is not None:
            self.severity_level = severity_level

    @property
    def message(self):
        """Gets the message of this EventsTraceInfo.  # noqa: E501

        The trace message  # noqa: E501

        :return: The message of this EventsTraceInfo.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this EventsTraceInfo.

        The trace message  # noqa: E501

        :param message: The message of this EventsTraceInfo.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def severity_level(self):
        """Gets the severity_level of this EventsTraceInfo.  # noqa: E501

        The trace severity level  # noqa: E501

        :return: The severity_level of this EventsTraceInfo.  # noqa: E501
        :rtype: int
        """
        return self._severity_level

    @severity_level.setter
    def severity_level(self, severity_level):
        """Sets the severity_level of this EventsTraceInfo.

        The trace severity level  # noqa: E501

        :param severity_level: The severity_level of this EventsTraceInfo.  # noqa: E501
        :type: int
        """

        self._severity_level = severity_level

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EventsTraceInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
