# coding: utf-8

"""
    AI public API

    This API exposes AI metric & event information and associated metadata  # noqa: E501

    OpenAPI spec version: v1
    Contact: aiapi@microsoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class EventsExceptionDetailsParsedStack(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'assembly': 'str',
        'method': 'str',
        'level': 'int',
        'line': 'int'
    }

    attribute_map = {
        'assembly': 'assembly',
        'method': 'method',
        'level': 'level',
        'line': 'line'
    }

    def __init__(self, assembly=None, method=None, level=None, line=None):  # noqa: E501
        """EventsExceptionDetailsParsedStack - a model defined in Swagger"""  # noqa: E501

        self._assembly = None
        self._method = None
        self._level = None
        self._line = None
        self.discriminator = None

        if assembly is not None:
            self.assembly = assembly
        if method is not None:
            self.method = method
        if level is not None:
            self.level = level
        if line is not None:
            self.line = line

    @property
    def assembly(self):
        """Gets the assembly of this EventsExceptionDetailsParsedStack.  # noqa: E501

        The assembly of the stack entry  # noqa: E501

        :return: The assembly of this EventsExceptionDetailsParsedStack.  # noqa: E501
        :rtype: str
        """
        return self._assembly

    @assembly.setter
    def assembly(self, assembly):
        """Sets the assembly of this EventsExceptionDetailsParsedStack.

        The assembly of the stack entry  # noqa: E501

        :param assembly: The assembly of this EventsExceptionDetailsParsedStack.  # noqa: E501
        :type: str
        """

        self._assembly = assembly

    @property
    def method(self):
        """Gets the method of this EventsExceptionDetailsParsedStack.  # noqa: E501

        The method of the stack entry  # noqa: E501

        :return: The method of this EventsExceptionDetailsParsedStack.  # noqa: E501
        :rtype: str
        """
        return self._method

    @method.setter
    def method(self, method):
        """Sets the method of this EventsExceptionDetailsParsedStack.

        The method of the stack entry  # noqa: E501

        :param method: The method of this EventsExceptionDetailsParsedStack.  # noqa: E501
        :type: str
        """

        self._method = method

    @property
    def level(self):
        """Gets the level of this EventsExceptionDetailsParsedStack.  # noqa: E501

        The level of the stack entry  # noqa: E501

        :return: The level of this EventsExceptionDetailsParsedStack.  # noqa: E501
        :rtype: int
        """
        return self._level

    @level.setter
    def level(self, level):
        """Sets the level of this EventsExceptionDetailsParsedStack.

        The level of the stack entry  # noqa: E501

        :param level: The level of this EventsExceptionDetailsParsedStack.  # noqa: E501
        :type: int
        """

        self._level = level

    @property
    def line(self):
        """Gets the line of this EventsExceptionDetailsParsedStack.  # noqa: E501

        The line of the stack entry  # noqa: E501

        :return: The line of this EventsExceptionDetailsParsedStack.  # noqa: E501
        :rtype: int
        """
        return self._line

    @line.setter
    def line(self, line):
        """Sets the line of this EventsExceptionDetailsParsedStack.

        The line of the stack entry  # noqa: E501

        :param line: The line of this EventsExceptionDetailsParsedStack.  # noqa: E501
        :type: int
        """

        self._line = line

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EventsExceptionDetailsParsedStack):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
