# coding: utf-8

"""
    AI public API

    This API exposes AI metric & event information and associated metadata  # noqa: E501

    OpenAPI spec version: v1
    Contact: aiapi@microsoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class EventsAiInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'i_key': 'str',
        'app_name': 'str',
        'app_id': 'str',
        'sdk_version': 'str'
    }

    attribute_map = {
        'i_key': 'iKey',
        'app_name': 'appName',
        'app_id': 'appId',
        'sdk_version': 'sdkVersion'
    }

    def __init__(self, i_key=None, app_name=None, app_id=None, sdk_version=None):  # noqa: E501
        """EventsAiInfo - a model defined in Swagger"""  # noqa: E501

        self._i_key = None
        self._app_name = None
        self._app_id = None
        self._sdk_version = None
        self.discriminator = None

        if i_key is not None:
            self.i_key = i_key
        if app_name is not None:
            self.app_name = app_name
        if app_id is not None:
            self.app_id = app_id
        if sdk_version is not None:
            self.sdk_version = sdk_version

    @property
    def i_key(self):
        """Gets the i_key of this EventsAiInfo.  # noqa: E501

        iKey of the app  # noqa: E501

        :return: The i_key of this EventsAiInfo.  # noqa: E501
        :rtype: str
        """
        return self._i_key

    @i_key.setter
    def i_key(self, i_key):
        """Sets the i_key of this EventsAiInfo.

        iKey of the app  # noqa: E501

        :param i_key: The i_key of this EventsAiInfo.  # noqa: E501
        :type: str
        """

        self._i_key = i_key

    @property
    def app_name(self):
        """Gets the app_name of this EventsAiInfo.  # noqa: E501

        Name of the application  # noqa: E501

        :return: The app_name of this EventsAiInfo.  # noqa: E501
        :rtype: str
        """
        return self._app_name

    @app_name.setter
    def app_name(self, app_name):
        """Sets the app_name of this EventsAiInfo.

        Name of the application  # noqa: E501

        :param app_name: The app_name of this EventsAiInfo.  # noqa: E501
        :type: str
        """

        self._app_name = app_name

    @property
    def app_id(self):
        """Gets the app_id of this EventsAiInfo.  # noqa: E501

        ID of the application  # noqa: E501

        :return: The app_id of this EventsAiInfo.  # noqa: E501
        :rtype: str
        """
        return self._app_id

    @app_id.setter
    def app_id(self, app_id):
        """Sets the app_id of this EventsAiInfo.

        ID of the application  # noqa: E501

        :param app_id: The app_id of this EventsAiInfo.  # noqa: E501
        :type: str
        """

        self._app_id = app_id

    @property
    def sdk_version(self):
        """Gets the sdk_version of this EventsAiInfo.  # noqa: E501

        SDK version of the application  # noqa: E501

        :return: The sdk_version of this EventsAiInfo.  # noqa: E501
        :rtype: str
        """
        return self._sdk_version

    @sdk_version.setter
    def sdk_version(self, sdk_version):
        """Sets the sdk_version of this EventsAiInfo.

        SDK version of the application  # noqa: E501

        :param sdk_version: The sdk_version of this EventsAiInfo.  # noqa: E501
        :type: str
        """

        self._sdk_version = sdk_version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EventsAiInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
