# coding: utf-8

"""
    AI public API

    This API exposes AI metric & event information and associated metadata  # noqa: E501

    OpenAPI spec version: v1
    Contact: aiapi@microsoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.applications_param import ApplicationsParam  # noqa: F401,E501
from swagger_client.models.query_param import QueryParam  # noqa: F401,E501
from swagger_client.models.query_timespan import QueryTimespan  # noqa: F401,E501


class QueryBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'query': 'QueryParam',
        'timespan': 'QueryTimespan',
        'applications': 'ApplicationsParam'
    }

    attribute_map = {
        'query': 'query',
        'timespan': 'timespan',
        'applications': 'applications'
    }

    def __init__(self, query=None, timespan=None, applications=None):  # noqa: E501
        """QueryBody - a model defined in Swagger"""  # noqa: E501

        self._query = None
        self._timespan = None
        self._applications = None
        self.discriminator = None

        self.query = query
        if timespan is not None:
            self.timespan = timespan
        if applications is not None:
            self.applications = applications

    @property
    def query(self):
        """Gets the query of this QueryBody.  # noqa: E501


        :return: The query of this QueryBody.  # noqa: E501
        :rtype: QueryParam
        """
        return self._query

    @query.setter
    def query(self, query):
        """Sets the query of this QueryBody.


        :param query: The query of this QueryBody.  # noqa: E501
        :type: QueryParam
        """
        if query is None:
            raise ValueError("Invalid value for `query`, must not be `None`")  # noqa: E501

        self._query = query

    @property
    def timespan(self):
        """Gets the timespan of this QueryBody.  # noqa: E501


        :return: The timespan of this QueryBody.  # noqa: E501
        :rtype: QueryTimespan
        """
        return self._timespan

    @timespan.setter
    def timespan(self, timespan):
        """Sets the timespan of this QueryBody.


        :param timespan: The timespan of this QueryBody.  # noqa: E501
        :type: QueryTimespan
        """

        self._timespan = timespan

    @property
    def applications(self):
        """Gets the applications of this QueryBody.  # noqa: E501


        :return: The applications of this QueryBody.  # noqa: E501
        :rtype: ApplicationsParam
        """
        return self._applications

    @applications.setter
    def applications(self, applications):
        """Sets the applications of this QueryBody.


        :param applications: The applications of this QueryBody.  # noqa: E501
        :type: ApplicationsParam
        """

        self._applications = applications

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QueryBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
