# coding: utf-8

"""
    AI public API

    This API exposes AI metric & event information and associated metadata  # noqa: E501

    OpenAPI spec version: v1
    Contact: aiapi@microsoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.column import Column  # noqa: F401,E501


class Table(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'columns': 'list[Column]',
        'rows': 'list[list[str]]'
    }

    attribute_map = {
        'name': 'name',
        'columns': 'columns',
        'rows': 'rows'
    }

    def __init__(self, name=None, columns=None, rows=None):  # noqa: E501
        """Table - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._columns = None
        self._rows = None
        self.discriminator = None

        self.name = name
        self.columns = columns
        self.rows = rows

    @property
    def name(self):
        """Gets the name of this Table.  # noqa: E501

        The name of the table.  # noqa: E501

        :return: The name of this Table.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Table.

        The name of the table.  # noqa: E501

        :param name: The name of this Table.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def columns(self):
        """Gets the columns of this Table.  # noqa: E501

        The list of columns in this table.  # noqa: E501

        :return: The columns of this Table.  # noqa: E501
        :rtype: list[Column]
        """
        return self._columns

    @columns.setter
    def columns(self, columns):
        """Sets the columns of this Table.

        The list of columns in this table.  # noqa: E501

        :param columns: The columns of this Table.  # noqa: E501
        :type: list[Column]
        """
        if columns is None:
            raise ValueError("Invalid value for `columns`, must not be `None`")  # noqa: E501

        self._columns = columns

    @property
    def rows(self):
        """Gets the rows of this Table.  # noqa: E501

        The resulting rows from this query.  # noqa: E501

        :return: The rows of this Table.  # noqa: E501
        :rtype: list[list[str]]
        """
        return self._rows

    @rows.setter
    def rows(self, rows):
        """Sets the rows of this Table.

        The resulting rows from this query.  # noqa: E501

        :param rows: The rows of this Table.  # noqa: E501
        :type: list[list[str]]
        """
        if rows is None:
            raise ValueError("Invalid value for `rows`, must not be `None`")  # noqa: E501

        self._rows = rows

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Table):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
